# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.models.schedule_game_teams_away_team import ScheduleGameTeamsAwayTeam  # noqa: E501
from powerplay.rest import ApiException


class TestScheduleGameTeamsAwayTeam(unittest.TestCase):
    """ScheduleGameTeamsAwayTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleGameTeamsAwayTeam(self):
        """Test ScheduleGameTeamsAwayTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerplay.models.schedule_game_teams_away_team.ScheduleGameTeamsAwayTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
