# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.models.player_current_team import PlayerCurrentTeam  # noqa: E501
from powerplay.rest import ApiException


class TestPlayerCurrentTeam(unittest.TestCase):
    """PlayerCurrentTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerCurrentTeam(self):
        """Test PlayerCurrentTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerplay.models.player_current_team.PlayerCurrentTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
