# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.models.game_play_about import GamePlayAbout  # noqa: E501
from powerplay.rest import ApiException


class TestGamePlayAbout(unittest.TestCase):
    """GamePlayAbout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGamePlayAbout(self):
        """Test GamePlayAbout"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerplay.models.game_play_about.GamePlayAbout()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
