# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.api.standings_api import StandingsApi  # noqa: E501
from powerplay.rest import ApiException


class TestStandingsApi(unittest.TestCase):
    """StandingsApi unit test stubs"""

    def setUp(self):
        self.api = StandingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_standing_types(self):
        """Test case for get_standing_types

        Get all available NHL standing types.  # noqa: E501
        """
        pass

    def test_get_standings(self):
        """Test case for get_standings

        Get NHL division standings.  # noqa: E501
        """
        pass

    def test_get_standings_by_type(self):
        """Test case for get_standings_by_type

        Get NHL standings for a specific standing type.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
