# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.models.venue_time_zone import VenueTimeZone  # noqa: E501
from powerplay.rest import ApiException


class TestVenueTimeZone(unittest.TestCase):
    """VenueTimeZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVenueTimeZone(self):
        """Test VenueTimeZone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.venue_time_zone.VenueTimeZone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
