# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.api.divisions_api import DivisionsApi  # noqa: E501
from powerplay.rest import ApiException


class TestDivisionsApi(unittest.TestCase):
    """DivisionsApi unit test stubs"""

    def setUp(self):
        self.api = DivisionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_division(self):
        """Test case for get_division

        Get an NHL division.  # noqa: E501
        """
        pass

    def test_get_divisions(self):
        """Test case for get_divisions

        Get all current NHL divisions.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
