# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.models.team_stats_splits import TeamStatsSplits  # noqa: E501
from powerplay.rest import ApiException


class TestTeamStatsSplits(unittest.TestCase):
    """TeamStatsSplits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamStatsSplits(self):
        """Test TeamStatsSplits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerplay.models.team_stats_splits.TeamStatsSplits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
