# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerplay
from powerplay.models.game_game_data_venue import GameGameDataVenue  # noqa: E501
from powerplay.rest import ApiException


class TestGameGameDataVenue(unittest.TestCase):
    """GameGameDataVenue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameGameDataVenue(self):
        """Test GameGameDataVenue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerplay.models.game_game_data_venue.GameGameDataVenue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
