# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameLinescorePowerPlayInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'situation_time_remaining': 'float',
        'situation_time_elapsed': 'float',
        'in_situation': 'bool'
    }

    attribute_map = {
        'situation_time_remaining': 'situationTimeRemaining',
        'situation_time_elapsed': 'situationTimeElapsed',
        'in_situation': 'inSituation'
    }

    def __init__(self, situation_time_remaining=None, situation_time_elapsed=None, in_situation=None):  # noqa: E501
        """GameLinescorePowerPlayInfo - a model defined in Swagger"""  # noqa: E501
        self._situation_time_remaining = None
        self._situation_time_elapsed = None
        self._in_situation = None
        self.discriminator = None
        if situation_time_remaining is not None:
            self.situation_time_remaining = situation_time_remaining
        if situation_time_elapsed is not None:
            self.situation_time_elapsed = situation_time_elapsed
        if in_situation is not None:
            self.in_situation = in_situation

    @property
    def situation_time_remaining(self):
        """Gets the situation_time_remaining of this GameLinescorePowerPlayInfo.  # noqa: E501


        :return: The situation_time_remaining of this GameLinescorePowerPlayInfo.  # noqa: E501
        :rtype: float
        """
        return self._situation_time_remaining

    @situation_time_remaining.setter
    def situation_time_remaining(self, situation_time_remaining):
        """Sets the situation_time_remaining of this GameLinescorePowerPlayInfo.


        :param situation_time_remaining: The situation_time_remaining of this GameLinescorePowerPlayInfo.  # noqa: E501
        :type: float
        """

        self._situation_time_remaining = situation_time_remaining

    @property
    def situation_time_elapsed(self):
        """Gets the situation_time_elapsed of this GameLinescorePowerPlayInfo.  # noqa: E501


        :return: The situation_time_elapsed of this GameLinescorePowerPlayInfo.  # noqa: E501
        :rtype: float
        """
        return self._situation_time_elapsed

    @situation_time_elapsed.setter
    def situation_time_elapsed(self, situation_time_elapsed):
        """Sets the situation_time_elapsed of this GameLinescorePowerPlayInfo.


        :param situation_time_elapsed: The situation_time_elapsed of this GameLinescorePowerPlayInfo.  # noqa: E501
        :type: float
        """

        self._situation_time_elapsed = situation_time_elapsed

    @property
    def in_situation(self):
        """Gets the in_situation of this GameLinescorePowerPlayInfo.  # noqa: E501


        :return: The in_situation of this GameLinescorePowerPlayInfo.  # noqa: E501
        :rtype: bool
        """
        return self._in_situation

    @in_situation.setter
    def in_situation(self, in_situation):
        """Sets the in_situation of this GameLinescorePowerPlayInfo.


        :param in_situation: The in_situation of this GameLinescorePowerPlayInfo.  # noqa: E501
        :type: bool
        """

        self._in_situation = in_situation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameLinescorePowerPlayInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameLinescorePowerPlayInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
