# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameLinescoreShootoutInfoAway(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scores': 'float',
        'attempts': 'float'
    }

    attribute_map = {
        'scores': 'scores',
        'attempts': 'attempts'
    }

    def __init__(self, scores=None, attempts=None):  # noqa: E501
        """GameLinescoreShootoutInfoAway - a model defined in Swagger"""  # noqa: E501
        self._scores = None
        self._attempts = None
        self.discriminator = None
        if scores is not None:
            self.scores = scores
        if attempts is not None:
            self.attempts = attempts

    @property
    def scores(self):
        """Gets the scores of this GameLinescoreShootoutInfoAway.  # noqa: E501


        :return: The scores of this GameLinescoreShootoutInfoAway.  # noqa: E501
        :rtype: float
        """
        return self._scores

    @scores.setter
    def scores(self, scores):
        """Sets the scores of this GameLinescoreShootoutInfoAway.


        :param scores: The scores of this GameLinescoreShootoutInfoAway.  # noqa: E501
        :type: float
        """

        self._scores = scores

    @property
    def attempts(self):
        """Gets the attempts of this GameLinescoreShootoutInfoAway.  # noqa: E501


        :return: The attempts of this GameLinescoreShootoutInfoAway.  # noqa: E501
        :rtype: float
        """
        return self._attempts

    @attempts.setter
    def attempts(self, attempts):
        """Sets the attempts of this GameLinescoreShootoutInfoAway.


        :param attempts: The attempts of this GameLinescoreShootoutInfoAway.  # noqa: E501
        :type: float
        """

        self._attempts = attempts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameLinescoreShootoutInfoAway, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameLinescoreShootoutInfoAway):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
