# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameGameDataStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'abstract_game_state': 'str',
        'coded_game_state': 'str',
        'detailed_state': 'str',
        'status_code': 'str',
        'start_time_tbd': 'bool'
    }

    attribute_map = {
        'abstract_game_state': 'abstractGameState',
        'coded_game_state': 'codedGameState',
        'detailed_state': 'detailedState',
        'status_code': 'statusCode',
        'start_time_tbd': 'startTimeTBD'
    }

    def __init__(self, abstract_game_state=None, coded_game_state=None, detailed_state=None, status_code=None, start_time_tbd=None):  # noqa: E501
        """GameGameDataStatus - a model defined in Swagger"""  # noqa: E501
        self._abstract_game_state = None
        self._coded_game_state = None
        self._detailed_state = None
        self._status_code = None
        self._start_time_tbd = None
        self.discriminator = None
        if abstract_game_state is not None:
            self.abstract_game_state = abstract_game_state
        if coded_game_state is not None:
            self.coded_game_state = coded_game_state
        if detailed_state is not None:
            self.detailed_state = detailed_state
        if status_code is not None:
            self.status_code = status_code
        if start_time_tbd is not None:
            self.start_time_tbd = start_time_tbd

    @property
    def abstract_game_state(self):
        """Gets the abstract_game_state of this GameGameDataStatus.  # noqa: E501


        :return: The abstract_game_state of this GameGameDataStatus.  # noqa: E501
        :rtype: str
        """
        return self._abstract_game_state

    @abstract_game_state.setter
    def abstract_game_state(self, abstract_game_state):
        """Sets the abstract_game_state of this GameGameDataStatus.


        :param abstract_game_state: The abstract_game_state of this GameGameDataStatus.  # noqa: E501
        :type: str
        """

        self._abstract_game_state = abstract_game_state

    @property
    def coded_game_state(self):
        """Gets the coded_game_state of this GameGameDataStatus.  # noqa: E501


        :return: The coded_game_state of this GameGameDataStatus.  # noqa: E501
        :rtype: str
        """
        return self._coded_game_state

    @coded_game_state.setter
    def coded_game_state(self, coded_game_state):
        """Sets the coded_game_state of this GameGameDataStatus.


        :param coded_game_state: The coded_game_state of this GameGameDataStatus.  # noqa: E501
        :type: str
        """

        self._coded_game_state = coded_game_state

    @property
    def detailed_state(self):
        """Gets the detailed_state of this GameGameDataStatus.  # noqa: E501


        :return: The detailed_state of this GameGameDataStatus.  # noqa: E501
        :rtype: str
        """
        return self._detailed_state

    @detailed_state.setter
    def detailed_state(self, detailed_state):
        """Sets the detailed_state of this GameGameDataStatus.


        :param detailed_state: The detailed_state of this GameGameDataStatus.  # noqa: E501
        :type: str
        """

        self._detailed_state = detailed_state

    @property
    def status_code(self):
        """Gets the status_code of this GameGameDataStatus.  # noqa: E501


        :return: The status_code of this GameGameDataStatus.  # noqa: E501
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this GameGameDataStatus.


        :param status_code: The status_code of this GameGameDataStatus.  # noqa: E501
        :type: str
        """

        self._status_code = status_code

    @property
    def start_time_tbd(self):
        """Gets the start_time_tbd of this GameGameDataStatus.  # noqa: E501


        :return: The start_time_tbd of this GameGameDataStatus.  # noqa: E501
        :rtype: bool
        """
        return self._start_time_tbd

    @start_time_tbd.setter
    def start_time_tbd(self, start_time_tbd):
        """Sets the start_time_tbd of this GameGameDataStatus.


        :param start_time_tbd: The start_time_tbd of this GameGameDataStatus.  # noqa: E501
        :type: bool
        """

        self._start_time_tbd = start_time_tbd

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameGameDataStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameGameDataStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
