# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameContentEditorial(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'preview': 'GameEditorials',
        'articles': 'GameEditorials',
        'recap': 'GameEditorials'
    }

    attribute_map = {
        'preview': 'preview',
        'articles': 'articles',
        'recap': 'recap'
    }

    def __init__(self, preview=None, articles=None, recap=None):  # noqa: E501
        """GameContentEditorial - a model defined in Swagger"""  # noqa: E501
        self._preview = None
        self._articles = None
        self._recap = None
        self.discriminator = None
        if preview is not None:
            self.preview = preview
        if articles is not None:
            self.articles = articles
        if recap is not None:
            self.recap = recap

    @property
    def preview(self):
        """Gets the preview of this GameContentEditorial.  # noqa: E501


        :return: The preview of this GameContentEditorial.  # noqa: E501
        :rtype: GameEditorials
        """
        return self._preview

    @preview.setter
    def preview(self, preview):
        """Sets the preview of this GameContentEditorial.


        :param preview: The preview of this GameContentEditorial.  # noqa: E501
        :type: GameEditorials
        """

        self._preview = preview

    @property
    def articles(self):
        """Gets the articles of this GameContentEditorial.  # noqa: E501


        :return: The articles of this GameContentEditorial.  # noqa: E501
        :rtype: GameEditorials
        """
        return self._articles

    @articles.setter
    def articles(self, articles):
        """Sets the articles of this GameContentEditorial.


        :param articles: The articles of this GameContentEditorial.  # noqa: E501
        :type: GameEditorials
        """

        self._articles = articles

    @property
    def recap(self):
        """Gets the recap of this GameContentEditorial.  # noqa: E501


        :return: The recap of this GameContentEditorial.  # noqa: E501
        :rtype: GameEditorials
        """
        return self._recap

    @recap.setter
    def recap(self, recap):
        """Sets the recap of this GameContentEditorial.


        :param recap: The recap of this GameContentEditorial.  # noqa: E501
        :type: GameEditorials
        """

        self._recap = recap

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameContentEditorial, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameContentEditorial):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
