# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameBoxscoreTeamTeam(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'name': 'str',
        'link': 'str',
        'abbreviation': 'str',
        'tri_code': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'link': 'link',
        'abbreviation': 'abbreviation',
        'tri_code': 'triCode'
    }

    def __init__(self, id=None, name=None, link=None, abbreviation=None, tri_code=None):  # noqa: E501
        """GameBoxscoreTeamTeam - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._link = None
        self._abbreviation = None
        self._tri_code = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if link is not None:
            self.link = link
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if tri_code is not None:
            self.tri_code = tri_code

    @property
    def id(self):
        """Gets the id of this GameBoxscoreTeamTeam.  # noqa: E501


        :return: The id of this GameBoxscoreTeamTeam.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GameBoxscoreTeamTeam.


        :param id: The id of this GameBoxscoreTeamTeam.  # noqa: E501
        :type: float
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GameBoxscoreTeamTeam.  # noqa: E501


        :return: The name of this GameBoxscoreTeamTeam.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GameBoxscoreTeamTeam.


        :param name: The name of this GameBoxscoreTeamTeam.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def link(self):
        """Gets the link of this GameBoxscoreTeamTeam.  # noqa: E501


        :return: The link of this GameBoxscoreTeamTeam.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this GameBoxscoreTeamTeam.


        :param link: The link of this GameBoxscoreTeamTeam.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def abbreviation(self):
        """Gets the abbreviation of this GameBoxscoreTeamTeam.  # noqa: E501


        :return: The abbreviation of this GameBoxscoreTeamTeam.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this GameBoxscoreTeamTeam.


        :param abbreviation: The abbreviation of this GameBoxscoreTeamTeam.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def tri_code(self):
        """Gets the tri_code of this GameBoxscoreTeamTeam.  # noqa: E501


        :return: The tri_code of this GameBoxscoreTeamTeam.  # noqa: E501
        :rtype: str
        """
        return self._tri_code

    @tri_code.setter
    def tri_code(self, tri_code):
        """Sets the tri_code of this GameBoxscoreTeamTeam.


        :param tri_code: The tri_code of this GameBoxscoreTeamTeam.  # noqa: E501
        :type: str
        """

        self._tri_code = tri_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameBoxscoreTeamTeam, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameBoxscoreTeamTeam):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
