# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameHighlightType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'topic_list': 'str',
        'items': 'list[GameHighlight]'
    }

    attribute_map = {
        'title': 'title',
        'topic_list': 'topicList',
        'items': 'items'
    }

    def __init__(self, title=None, topic_list=None, items=None):  # noqa: E501
        """GameHighlightType - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._topic_list = None
        self._items = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if topic_list is not None:
            self.topic_list = topic_list
        if items is not None:
            self.items = items

    @property
    def title(self):
        """Gets the title of this GameHighlightType.  # noqa: E501


        :return: The title of this GameHighlightType.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this GameHighlightType.


        :param title: The title of this GameHighlightType.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def topic_list(self):
        """Gets the topic_list of this GameHighlightType.  # noqa: E501


        :return: The topic_list of this GameHighlightType.  # noqa: E501
        :rtype: str
        """
        return self._topic_list

    @topic_list.setter
    def topic_list(self, topic_list):
        """Sets the topic_list of this GameHighlightType.


        :param topic_list: The topic_list of this GameHighlightType.  # noqa: E501
        :type: str
        """

        self._topic_list = topic_list

    @property
    def items(self):
        """Gets the items of this GameHighlightType.  # noqa: E501


        :return: The items of this GameHighlightType.  # noqa: E501
        :rtype: list[GameHighlight]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this GameHighlightType.


        :param items: The items of this GameHighlightType.  # noqa: E501
        :type: list[GameHighlight]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameHighlightType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameHighlightType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
