# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GamePlayPlayers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'player': 'GamePlayPlayer',
        'player_type': 'str'
    }

    attribute_map = {
        'player': 'player',
        'player_type': 'playerType'
    }

    def __init__(self, player=None, player_type=None):  # noqa: E501
        """GamePlayPlayers - a model defined in Swagger"""  # noqa: E501
        self._player = None
        self._player_type = None
        self.discriminator = None
        if player is not None:
            self.player = player
        if player_type is not None:
            self.player_type = player_type

    @property
    def player(self):
        """Gets the player of this GamePlayPlayers.  # noqa: E501


        :return: The player of this GamePlayPlayers.  # noqa: E501
        :rtype: GamePlayPlayer
        """
        return self._player

    @player.setter
    def player(self, player):
        """Sets the player of this GamePlayPlayers.


        :param player: The player of this GamePlayPlayers.  # noqa: E501
        :type: GamePlayPlayer
        """

        self._player = player

    @property
    def player_type(self):
        """Gets the player_type of this GamePlayPlayers.  # noqa: E501


        :return: The player_type of this GamePlayPlayers.  # noqa: E501
        :rtype: str
        """
        return self._player_type

    @player_type.setter
    def player_type(self, player_type):
        """Sets the player_type of this GamePlayPlayers.


        :param player_type: The player_type of this GamePlayPlayers.  # noqa: E501
        :type: str
        """

        self._player_type = player_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GamePlayPlayers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GamePlayPlayers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
