# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Roster(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'person': 'RosterPerson',
        'jersey_number': 'float',
        'position': 'DraftProspectPrimaryPosition'
    }

    attribute_map = {
        'person': 'person',
        'jersey_number': 'jerseyNumber',
        'position': 'position'
    }

    def __init__(self, person=None, jersey_number=None, position=None):  # noqa: E501
        """Roster - a model defined in Swagger"""  # noqa: E501
        self._person = None
        self._jersey_number = None
        self._position = None
        self.discriminator = None
        if person is not None:
            self.person = person
        if jersey_number is not None:
            self.jersey_number = jersey_number
        if position is not None:
            self.position = position

    @property
    def person(self):
        """Gets the person of this Roster.  # noqa: E501


        :return: The person of this Roster.  # noqa: E501
        :rtype: RosterPerson
        """
        return self._person

    @person.setter
    def person(self, person):
        """Sets the person of this Roster.


        :param person: The person of this Roster.  # noqa: E501
        :type: RosterPerson
        """

        self._person = person

    @property
    def jersey_number(self):
        """Gets the jersey_number of this Roster.  # noqa: E501


        :return: The jersey_number of this Roster.  # noqa: E501
        :rtype: float
        """
        return self._jersey_number

    @jersey_number.setter
    def jersey_number(self, jersey_number):
        """Sets the jersey_number of this Roster.


        :param jersey_number: The jersey_number of this Roster.  # noqa: E501
        :type: float
        """

        self._jersey_number = jersey_number

    @property
    def position(self):
        """Gets the position of this Roster.  # noqa: E501


        :return: The position of this Roster.  # noqa: E501
        :rtype: DraftProspectPrimaryPosition
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Roster.


        :param position: The position of this Roster.  # noqa: E501
        :type: DraftProspectPrimaryPosition
        """

        self._position = position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Roster, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Roster):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
