# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VenueTimeZone(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'offset': 'float',
        'tz': 'str'
    }

    attribute_map = {
        'id': 'id',
        'offset': 'offset',
        'tz': 'tz'
    }

    def __init__(self, id=None, offset=None, tz=None):  # noqa: E501
        """VenueTimeZone - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._offset = None
        self._tz = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if offset is not None:
            self.offset = offset
        if tz is not None:
            self.tz = tz

    @property
    def id(self):
        """Gets the id of this VenueTimeZone.  # noqa: E501


        :return: The id of this VenueTimeZone.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VenueTimeZone.


        :param id: The id of this VenueTimeZone.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def offset(self):
        """Gets the offset of this VenueTimeZone.  # noqa: E501


        :return: The offset of this VenueTimeZone.  # noqa: E501
        :rtype: float
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this VenueTimeZone.


        :param offset: The offset of this VenueTimeZone.  # noqa: E501
        :type: float
        """

        self._offset = offset

    @property
    def tz(self):
        """Gets the tz of this VenueTimeZone.  # noqa: E501


        :return: The tz of this VenueTimeZone.  # noqa: E501
        :rtype: str
        """
        return self._tz

    @tz.setter
    def tz(self, tz):
        """Sets the tz of this VenueTimeZone.


        :param tz: The tz of this VenueTimeZone.  # noqa: E501
        :type: str
        """

        self._tz = tz

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VenueTimeZone, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VenueTimeZone):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
